alter table CASCADEDLOOKUPS_CITY add constraint FK_CASCADEDLOOKUPS_CITY_ON_COUNTRY foreign key (COUNTRY_ID) references CASCADEDLOOKUPS_COUNTRY(ID);
create index IDX_CASCADEDLOOKUPS_CITY_ON_COUNTRY on CASCADEDLOOKUPS_CITY (COUNTRY_ID);
