alter table CASCADEDLOOKUPS_ADDRESS add constraint FK_CASCADEDLOOKUPS_ADDRESS_ON_CITY foreign key (CITY_ID) references CASCADEDLOOKUPS_CITY(ID);
alter table CASCADEDLOOKUPS_ADDRESS add constraint FK_CASCADEDLOOKUPS_ADDRESS_ON_COUNTRY foreign key (COUNTRY_ID) references CASCADEDLOOKUPS_COUNTRY(ID);
create index IDX_CASCADEDLOOKUPS_ADDRESS_ON_CITY on CASCADEDLOOKUPS_ADDRESS (CITY_ID);
create index IDX_CASCADEDLOOKUPS_ADDRESS_ON_COUNTRY on CASCADEDLOOKUPS_ADDRESS (COUNTRY_ID);
